### ISSUE TITLE
[BUG] Error: Failed to load the visual affect. Please choose another visual effect in the configuration dialog.

### ISSUE THREAD

**Issue by KOT040188** [rbn42/panon#121]
**Desktop (please complete the following information):**
 - OS: opensuse tumbleweed
 - Version of Plasma Framework 5.113.0

**Describe the bug**
The widget doesn't work https://imgur.com/a/zTcVB9c I tried all the effects from the menu - zero reaction
**Any error message shown in the console**
Please execute the following commands in the console and upload the outputs.

git clone https://github.com/rbn42/panon.git
cd panon
git submodule update --init
# You need to install plasma-sdk to get plasmoidviewer.
plasmoidviewer --applet ./plasmoid/

`kot@192:~/panon$ plasmoidviewer --applet ./plasmoid/
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
kf.plasma.quick: Applet preload policy set to 1
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentInterface(0x5652e2715b30)
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
kf.kio.core: Invalid URL: QUrl("")
file:///home/kot/panon/plasmoid/contents/ui/Spectrum.qml:95:45: QML Image: Unknown error
org.kde.plasma.containmentlayoutmanager: Trying to take space not available BasicAppletContainer_QMLTYPE_151_QML_170(0x5652e24504f0, parent=0x5652e26ce380, geometry=320,240 640x192)
qml: JSON parse error
qml: Executed command:
qml: cd "/home/kot/panon/plasmoid/contents/scripts";python3 -m panon.effect.build_shader_source WyIiLFtdXQ==
qml: JSON content:
qml: 
qml: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/kot/panon/plasmoid/contents/scripts/panon/effect/build_shader_source.py", line 5, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'

qml: 
qml: 

`
It doesn't work in plasmoidviewer either.

**Comment by anjelpsy** [comment]
I am experiencing the same issue. (Failed to load visual effect, tried most of the options).
OS: Slackware current
KDE Plasma version 5.27.11
KDE Frameworks version: 5.116.0
Qt version 5.15.16

/tmp/panontest/panon # git submodule update --init
Submodule 'SoundCard' (https://github.com/bastibe/SoundCard) registered for path 'third_party/SoundCard'
Submodule 'hsluv-glsl' (https://github.com/williammalo/hsluv-glsl) registered for path 'third_party/hsluv-glsl'
Cloning into '/tmp/panontest/panon/third_party/SoundCard'...
Cloning into '/tmp/panontest/panon/third_party/hsluv-glsl'...
Submodule path 'third_party/SoundCard': checked out '745771575e56ab4c5ebf7118816e457c8e6b1b3d'
Submodule path 'third_party/hsluv-glsl': checked out '0ca50ad85bd879f2f71bcfda2adaa98049aaaa50'

/tmp/panontest/panon # ./test.sh 
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
kf.plasma.quick: Applet preload policy set to 1
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentInterface(0x2193adc0)
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
kf.kio.core: Invalid URL: QUrl("")
file:///tmp/panontest/panon/plasmoid/contents/ui/Spectrum.qml:95:45: QML Image: Unknown error
org.kde.plasma.containmentlayoutmanager: Trying to take space not available BasicAppletContainer_QMLTYPE_160_QML_170(0x2180ec30, parent=0x219e96d0, geometry=320,240 640x96)
qml: JSON parse error
qml: Executed command:
qml: cd "/tmp/panontest/panon/plasmoid/contents/scripts";python3 -m panon.effect.build_shader_source WyIiLFtdXQ==
qml: JSON content:
qml: 
qml: Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/panontest/panon/plasmoid/contents/scripts/panon/effect/build_shader_source.py", line 5, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'

org.kde.plasma.containmentlayoutmanager: Trying to take space not available BasicAppletContainer_QMLTYPE_160_QML_170(0x2180ec30, parent=0x219e96d0, geometry=320,240 640x96)
qml: 
qml: 
"Applet panon does not exist."
