### ISSUE TITLE
QQuickOpenGLShaderEffect: 'source' does not have a matching property

### ISSUE THREAD

**Issue by kkkaroth** [rbn42/panon#21]
panon does't working, the system log
``` shell
2020/3/9 上午12:39	plasmashell	adding "panon"
2020/3/9 上午12:39	plasmashell	QQuickOpenGLShaderEffect: 'source' does not have a matching property!
2020/3/9 上午12:39	plasmashell	QQuickOpenGLShaderEffect: 'source' does not have a matching property!
2020/3/9 上午12:39	plasmashell	kf5.kio.core: Invalid URL: QUrl("")
2020/3/9 上午12:39	plasmashell	trying to show an empty dialog
2020/3/9 上午12:39	plasmashell	file:///home/custom/.local/share/plasma/plasmoids/panon/contents/ui/Spectrum.qml:120:45: QML Image: Unknown error
```
what can i do?

**Comment by rbn42** [comment]
Hi kkkaroth, please execute these commands and tell me the outputs, thank you.
```sh
git clone https://github.com/rbn42/panon.git
cd panon
# Download SoundCard and hsluv-glsl
git submodule update --init
# Install plasma-sdk to get plasmoidviewer.
plasmoidviewer --applet ./plasmoid/
```

**Comment by kkkaroth** [comment]
> Hi kkkaroth, please execute these commands and tell me the outputs, thank you.
> 
> ```shell
> git clone https://github.com/rbn42/panon.git
> cd panon
> # Download SoundCard and hsluv-glsl
> git submodule update --init
> # Install plasma-sdk to get plasmoidviewer.
> plasmoidviewer --applet ./plasmoid/
> ```

Hi rbn42,  maybe these can help you

```shell
org.kde.plasma: invalid metadata "/usr/lib/qt/plugins/kontact_kaddressbookplugin.so"
org.kde.plasmaquick: Applet preload policy set to 1
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:76:9: Unable to assign [undefined] to QStringList
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:75:9: Unable to assign [undefined] to int
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:75:9: Unable to assign [undefined] to int
file:///usr/share/plasma/wallpapers/org.kde.image/contents/ui/main.qml:76:9: Unable to assign [undefined] to QStringList
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentInterface(0x55d55b4822c0)
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
kf5.kio.core: Invalid URL: QUrl("")
trying to show an empty dialog
file:///home/custom/git/panon/plasmoid/contents/ui/Spectrum.qml:121:45: QML Image: Unknown error
QProcess: Destroyed while process ("/bin/sh") is still running.
qml: 
qml: ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/custom/git/panon/plasmoid/contents/scripts/panon/backend/client.py", line 111, in <module>
    asyncio.get_event_loop().run_until_complete(hello())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/custom/git/panon/plasmoid/contents/scripts/panon/backend/client.py", line 77, in hello
    latest_wave_data = spectrum_source.read()
  File "/home/custom/git/panon/plasmoid/contents/scripts/panon/backend/source.py", line 23, in read
    result = self.stream.read(self.chunk)
  File "/usr/lib/python3.8/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed

trying to show an empty dialog
```

**Comment by rbn42** [comment]
I think it is very likely that this issue should belong to pyaudio(PortAudio). But in your case, you can just try a different back-end instead, try soundcard(PulseAudio), or fifo if you use mpd.

https://i.loli.net/2020/03/09/PiM8GWQ1ahOK7xR.png

Image uploading speed from China to github is really slow these days.😡

**Comment by rbn42** [comment]
This issue may be related:
https://stackoverflow.com/questions/48777224/trying-to-understand-pyaudio-error-errno-9981-input-overflowed

And there is a possible solution. If you want to help try this solution, please replace this line 

File "/home/custom/git/panon/plasmoid/contents/scripts/panon/backend/source.py", line 23, in read
    result = self.stream.read(self.chunk)

with

    result = self.stream.read(self.chunk,exception_on_overflow = False)

**Comment by kkkaroth** [comment]
> This issue may be related:
> https://stackoverflow.com/questions/48777224/trying-to-understand-pyaudio-error-errno-9981-input-overflowed
> 
> And there is a possible solution. If you want to help try this solution, please replace this line
> 
> File "/home/custom/git/panon/plasmoid/contents/scripts/panon/backend/source.py", line 23, in read
> result = self.stream.read(self.chunk)
> 
> with
> 
> ```
> result = self.stream.read(self.chunk,exception_on_overflow = False)
> ```

Oh, thanks. Replace this line and  execute `plasmoidviewer applet ./plasmoid/`, everything works great! 

It‘s obvious that the cause of this problem is PyAudio.
