### ISSUE TITLE
Failed to load the visual effect. Please choose another effect in the configuration file.

### ISSUE THREAD

**Issue by iobaidurrehman** [rbn42/panon#68]
**Desktop (please complete the following information):**
 - OS: Manjaro 5.13.19-2
 - Plasma Version: 5.22.5
 - Version of Plasma Framework: 5.86.0

**Describe the bug**
Panon was working fine for a few days. Recently when I rebooted the system, the widget is showing: Failed to load the visual effect. Please choose another effect in the configuration file.

I do not see any input device in the back-end when I select PulseAudio. It only shows 01 device named "default". Also, I followed steps to remove NewStuff, restarted and nothing worked.

I love Panon and hoping the issue gets resolved soon.

**Any error message shown in the console**
Please execute the following commands in the console and upload the outputs.
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
kf.plasma.quick: Applet preload policy set to 1
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentInterface(0x558485842ea0)
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
kf.kio.core: Invalid URL: QUrl("")
trying to show an empty dialog
libpng warning: iCCP: known incorrect sRGB profile
file:///home/obaid/panon/plasmoid/contents/ui/Spectrum.qml:95:45: QML Image: Unknown error
qml: JSON parse error
qml: Executed command:
qml: cd "/home/obaid/panon/plasmoid/contents/scripts";python3 -m panon.effect.build_shader_source WyIiLFtdXQ==
qml: JSON content:
qml: 
qml: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/obaid/panon/plasmoid/contents/scripts/panon/effect/build_shader_source.py", line 5, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'

qml: 
qml: 
trying to show an empty dialog

**Comment by yigitlevent** [comment]
I have the exact same issue. Error message is the same, I'm hoping for a fix soon! :)

**Comment by nmanpkr** [comment]
Ran in to this issue today, solved it by installing the needed python dependencies. 
sudo apt install python3-docopt
sudo apt install python3-websockets
sudo apt install python3-pyaudio
