### ISSUE TITLE
Error: Failed to load the visual effect.

### ISSUE THREAD

**Issue by RagNarok-10** [rbn42/panon#75]
HI GUYS ! 

I am newbie on Linux 
I want panon on my desktop, but i am facing some error 
i dont know to fix that 

MY full SYSTEM SPEC is as followed -

 OS: Arch Linux / Manjaro kde 
 kde framwork - 5.88.0
 Plasma - 5.23.3 

FULL SYSTEM specs :- 
Operating System: Manjaro Linux
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.88.0
Qt Version: 5.15.2
Kernel Version: 5.13.19-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 2 × Pentium® Dual-Core CPU T4200 @ 2.00GHz
Memory: 3.8 GiB of RAM
Graphics Processor: Mesa DRI Mobile Intel® GM45 Express Chipset
  

I installed Panon from KDE WIDGET STORE 
I got this following ERROR :-

**Error**: Failed to load the visual effect. Please choose another visual effect in the configuration dialog

HOW CAN I FIX THIS !!

THANKS !!

**Comment by FlorianBr** [comment]
Check the requirements and install all necessary dependencies mentioned in the README. I had that error too because one of the python packages wasn't installed

**Comment by writeblankspace** [comment]
I have the same problem, ran the Arch Linux command but got this:
```
:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 python-pydantic-1.10.5-1-x86_64.pkg.tar.zst failed to download
 python-trove-classifiers-2023.2.20-1-any.pkg.tar.zst failed to download
 Total (2/2)                  1882.5 KiB   275 KiB/s 00:07 [-------------------------------] 100%
error: failed retrieving file 'python-pydantic-1.10.5-1-x86_64.pkg.tar.zst' from archlinux.uk.mirror.allworldit.com : The requested URL returned error: 404
error: failed retrieving file 'python-trove-classifiers-2023.2.20-1-any.pkg.tar.zst' from archlinux.uk.mirror.allworldit.com : The requested URL returned error: 404
error: failed retrieving file 'python-pydantic-1.10.5-1-x86_64.pkg.tar.zst' from mirrors.melbourne.co.uk : The requested URL returned error: 404
error: failed retrieving file 'python-trove-classifiers-2023.2.20-1-any.pkg.tar.zst' from mirrors.melbourne.co.uk : The requested URL returned error: 404
error: failed retrieving file 'python-pydantic-1.10.5-1-x86_64.pkg.tar.zst' from lon.mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'python-trove-classifiers-2023.2.20-1-any.pkg.tar.zst' from lon.mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'python-trove-classifiers-2023.2.20-1-any.pkg.tar.zst' from repo.slithery.uk : The requested URL returned error: 404
error: failed retrieving file 'python-pydantic-1.10.5-1-x86_64.pkg.tar.zst' from repo.slithery.uk : The requested URL returned error: 404
error: failed retrieving file 'python-trove-classifiers-2023.2.20-1-any.pkg.tar.zst' from mirror.cov.ukservers.com : The requested URL returned error: 404
error: failed retrieving file 'python-pydantic-1.10.5-1-x86_64.pkg.tar.zst' from mirror.cov.ukservers.com : The requested URL returned error: 404
error: failed retrieving file 'python-trove-classifiers-2023.2.20-1-any.pkg.tar.zst' from mirrors.gethosted.online : The requested URL returned error: 404
error: failed retrieving file 'python-pydantic-1.10.5-1-x86_64.pkg.tar.zst' from mirrors.gethosted.online : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit transaction (failed to retrieve some files)
Errors occurred, no packages were upgraded.
```

I tried debugging it using [these instructions](https://github.com/rbn42/panon/wiki/VisualEffects#debugging) and got this:
```
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
kf.plasma.quick: Applet preload policy set to 1
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentInterface(0x55bb039c6520)
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
org.kde.plasma.containmentlayoutmanager: Trying to take space not available BasicAppletContainer_QMLTYPE_177_QML_197(0x55bb03bf11d0, parent=0x55bb0380a700, geometry=320,240 640x96)
kf.kio.core: Invalid URL: QUrl("")
file:///home/user/Downloads/plasmoid/contents/ui/Spectrum.qml:95:45: QML Image: Unknown error
qml: JSON parse error
qml: Executed command:
qml: cd "/home/user/Downloads/plasmoid/contents/scripts";python3 -m panon.effect.build_shader_source WyIiLFtdXQ==
qml: JSON content:
qml: 
qml: Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/Downloads/plasmoid/contents/scripts/panon/effect/build_shader_source.py", line 5, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'

qml: 
qml: 
org.kde.plasma.containmentlayoutmanager: Trying to take space not available BasicAppletContainer_QMLTYPE_177_QML_197(0x55bb03bf11d0, parent=0x55bb0380a700, geometry=250.304,240 640x96)
```

EDIT: fixed using `pip install docopt` (make sure python and pip are installed)
