### ISSUE TITLE
[BUG] Panon is not working anymore.

### ISSUE THREAD

**Issue by onurbbr** [rbn42/panon#84]
**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version of Plasma Framework: 5.90

**Describe the bug**
Panon no longer works. Python related problem.

**Any error message shown in the console**
[onur@archlinux plasmoids]$ plasmoidviewer --applet panon/
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
kf.plasma.quick: Applet preload policy set to 1
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentInterface(0x55ca859e8ed0)
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
trying to show an empty dialog
kf.kio.core: Invalid URL: QUrl("")
Trying to take space not available BasicAppletContainer_QMLTYPE_185_QML_194(0x55ca86ec2e90, parent=0x55ca85d4d380, geometry=320,240 640x96)
file:///usr/share/plasma/plasmoids/panon/contents/ui/Spectrum.qml:95:45: QML Image: Unknown error
Trying to take space not available BasicAppletContainer_QMLTYPE_185_QML_194(0x55ca86ec2e90, parent=0x55ca85d4d380, geometry=320,240 640x96)
qml: 
qml: 
trying to show an empty dialog
QQmlEngine::setContextForObject(): Object already has a QQmlContext
file:///usr/share/plasma/shells/org.kde.plasma.plasmoidviewershell/contents/configuration/ConfigurationAppletPage.qml:35:5: QML Loader: Binding loop detected for property "height"
file:///usr/lib/qt/qml/org/kde/kirigami.2/FormLayout.qml:283:9: QML QQuickItem* (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "preferredWidth"
file:///usr/share/plasma/shells/org.kde.plasma.plasmoidviewershell/contents/configuration/ConfigurationAppletPage.qml:35:5: QML Loader: Binding loop detected for property "height"
file:///usr/lib/qt/qml/org/kde/kirigami.2/private/globaltoolbar/BreadcrumbControl.qml:17:5: Unable to assign [undefined] to QQuickItem*
file:///usr/share/plasma/shells/org.kde.plasma.plasmoidviewershell/contents/configuration/AppletConfiguration.qml:198: TypeError: Cannot read property 'source' of null
file:///usr/share/plasma/shells/org.kde.plasma.plasmoidviewershell/contents/configuration/AppletConfiguration.qml:198: TypeError: Cannot read property 'source' of null
file:///usr/share/plasma/shells/org.kde.plasma.plasmoidviewershell/contents/configuration/AppletConfiguration.qml:198: TypeError: Cannot read property 'source' of null
file:///usr/share/plasma/shells/org.kde.plasma.plasmoidviewershell/contents/configuration/AppletConfiguration.qml:198: TypeError: Cannot read property 'source' of null
file:///usr/share/plasma/shells/org.kde.plasma.plasmoidviewershell/contents/configuration/AppletConfiguration.qml:198: TypeError: Cannot read property 'source' of null
file:///usr/share/plasma/shells/org.kde.plasma.plasmoidviewershell/contents/configuration/AppletConfiguration.qml:198: TypeError: Cannot read property 'source' of null
file:///usr/lib/qt/qml/org/kde/kirigami.2/private/globaltoolbar/BreadcrumbControl.qml:17:5: Unable to assign [undefined] to QQuickItem*
file:///usr/lib/qt/qml/org/kde/kirigami.2/private/globaltoolbar/BreadcrumbControl.qml:17:5: Unable to assign [undefined] to QQuickItem*
file:///usr/share/plasma/plasmoids/panon/contents/ui/config/ConfigBackend.qml:10:1: QML ConfigBackend (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "preferredHeight"
QProcess: Destroyed while process ("/bin/sh") is still running.
qml: 
qml: Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/share/plasma/plasmoids/panon/contents/scripts/panon/backend/client.py", line 53, in <module>
    spectrum_source = source.SoundCardSource(spectrum.NUM_CHANNEL, sample_rate, arguments['--device-index'], cfg_fps)
  File "/usr/share/plasma/plasmoids/panon/contents/scripts/panon/backend/source.py", line 113, in __init__
    self.start()
  File "/usr/share/plasma/plasmoids/panon/contents/scripts/panon/backend/source.py", line 172, in start
    stream.__enter__()
  File "/usr/lib/python3.10/site-packages/soundcard/pulseaudio.py", line 638, in __enter__
    if isinstance(self.channels, collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'

**Comment by bpc1** [comment]
same issue as https://github.com/rbn42/panon/issues/78

**Comment by cyqsimon** [comment]
@bpc1 Not the same as #78. That was due to an issue with `python-soundcard`, which was easily fixable.

I applied the fix locally and panon worked for a few weeks, but then it just broke randomly after one of the updates. I've verified that the patch I've made to `soundcard` is still there, so this is very likely a different issue.

I've had no success trying to debug the issue using `journalctl`.
