### ISSUE TITLE
[BUG] Panon Broken With Plasma 5.25 and Frameworks 5.94

### ISSUE THREAD

**Issue by Nano-Ocelot** [rbn42/panon#94]
- OS: OpenSUSE Tumbleweed
 - Version of Plasma Framework: 5.94

Instead of the visual effect showing, a message saying, "Error: Failed to load the visual effect. Please choose another visual effect in the coniguration dialog," shows up. None of the other visual effects work either.

**Any error message shown in the console**
```
plasmoidviewer --applet ./plasmoid/                                                                                                              stable
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
kf.plasma.quick: Applet preload policy set to 1
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentInterface(0x55bf9fd71e40)
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
QQuickOpenGLShaderEffect: 'source' does not have a matching property!
kf.kio.core: Invalid URL: QUrl("")
file:///home/user/Git/panon/plasmoid/contents/ui/Spectrum.qml:95:45: QML Image: Unknown error
org.kde.plasma.containmentlayoutmanager: Trying to take space not available BasicAppletContainer_QMLTYPE_146_QML_165(0x55bf9f7599b0, parent=0x55bf9fad01c0, geometry=320,240 640x96)
org.kde.plasma.containmentlayoutmanager: Trying to take space not available BasicAppletContainer_QMLTYPE_146_QML_165(0x55bf9f7599b0, parent=0x55bf9fad01c0, geometry=320,240 640x96)
qml: JSON parse error
qml: Executed command:
qml: cd "/home/user/Git/panon/plasmoid/contents/scripts";python3 -m panon.effect.build_shader_source WyIiLFtdXQ==
qml: JSON content:
qml: 
qml: Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/Git/panon/plasmoid/contents/scripts/panon/effect/build_shader_source.py", line 5, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'

qml: 
qml: 
trying to show an empty dialog
```

**Comment by Feefkroete** [comment]
Same here
Also using Tumbleweed
Edit: Install all the dependencies listed in the README file.

**Comment by Nano-Ocelot** [comment]
> Same here Also using Tumbleweed Edit: Install all the dependencies listed in the README file.

That fixed it!

**Comment by Nano-Ocelot** [comment]
Actually I just double checked it again and it still doesn't work. The error doesn't appear on the panel anymore but neither does any effects. It just does nothing. I have all up to date dependencies and have tried building from source and installing the prebuilt plasmoid. 

Also important to note that I use pipewire, though that wasn't an issue before the big Plasma 5.25 and Plasma Frameworks 5.94 update.
I'm on Plasma 5.25.3 and Frameworks 5.96.0 now.

**Comment by FlyingRatBull** [comment]
Can confirm after upgrade to Kubuntu 22.02 with Plasma 5.24.4, Frameworks 5.92.0 and Qt 5.13.0.

* I get no error messages but it just doesn't work anymore.
* Dependencies are all installed and up-to-date. 
* Tried different visual effects
* Tried different backends

**Comment by renyuneyun** [comment]
I also noticed it no longer show visual effects now. Tracking back in time, I haven't seen it for months, but didn't really notice that.

**Comment by renyuneyun** [comment]
Did you check your Python version?
I have a similar issue, which turns out to be a compatibility issue with Python 3.10. See #107 and #108 .
